// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('LogIn', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LogIn', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1550, height: 830 })
    await driver.findElement(By.css("input:nth-child(2)")).click()
    await driver.findElement(By.css("input:nth-child(2)")).click()
    await driver.findElement(By.css("input:nth-child(2)")).click()
    await driver.findElement(By.css("input:nth-child(3)")).sendKeys("garamyoon")
    await driver.findElement(By.css("input:nth-child(2)")).sendKeys("garamyoon123@gamil.com")
    await driver.findElement(By.css("button:nth-child(4)")).click()
  })
})
